# Gradle settings
org.gradle.jvmargs=-Xmx1G -Djava.net.preferIPv6Addresses=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Shared mod properties
mod_group_id=org.yanbwe
mod_id=raritycore
mod_name=RarityCore
mod_license=GNU GPL 3.0

# 26.1 version properties
mod_version_26_1=2601.13.7
minecraft_version_26_1=26.1
minecraft_version_range_26_1=[26.1,26.2)
neo_version_26_1=26.1.0.8-beta

# 26.2 version properties
mod_version_26_2=2602.13.6
minecraft_version_26_2=26.2
minecraft_version_range_26_2=[26.2,26.3)
neo_version_26_2=26.2.0.57
